# Generated by Django 5.2.9 on 2026-01-05 22:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealers', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('total_vehicles', models.PositiveIntegerField(default=0)),
                ('active_vehicles', models.PositiveIntegerField(default=0)),
                ('vehicles_sold', models.PositiveIntegerField(default=0)),
                ('offers_received', models.PositiveIntegerField(default=0)),
                ('offers_accepted', models.PositiveIntegerField(default=0)),
                ('offers_rejected', models.PositiveIntegerField(default=0)),
                ('avg_response_time_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('avg_discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('conversion_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='dealers.dealer')),
            ],
            options={
                'verbose_name': 'dealer metrics',
                'verbose_name_plural': 'dealer metrics',
                'ordering': ['-date'],
                'unique_together': {('dealer', 'date')},
            },
        ),
        migrations.CreateModel(
            name='VehicleView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'vehicle view',
                'verbose_name_plural': 'vehicle views',
                'indexes': [models.Index(fields=['vehicle', '-created_at'], name='analytics_v_vehicle_762af2_idx'), models.Index(fields=['-created_at'], name='analytics_v_created_a0cbc5_idx')],
            },
        ),
    ]
