# Generated by Django 5.2.9 on 2026-01-05 22:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_name', models.CharField(db_index=True, max_length=200)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('tax_id', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(db_index=True, max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], db_index=True, default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'dealer',
                'verbose_name_plural': 'dealers',
            },
        ),
        migrations.CreateModel(
            name='DealerDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('license', 'Dealer License'), ('insurance', 'Insurance Certificate'), ('w9', 'W-9 Form'), ('bank_verification', 'Bank Account Verification'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='dealer_documents/')),
                ('filename', models.CharField(max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='dealers.dealer')),
            ],
            options={
                'verbose_name': 'dealer document',
                'verbose_name_plural': 'dealer documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dealer',
            index=models.Index(fields=['verification_status'], name='dealers_dea_verific_080330_idx'),
        ),
        migrations.AddIndex(
            model_name='dealer',
            index=models.Index(fields=['city', 'state'], name='dealers_dea_city_336d6d_idx'),
        ),
        migrations.AddIndex(
            model_name='dealer',
            index=models.Index(fields=['latitude', 'longitude'], name='dealers_dea_latitud_11548e_idx'),
        ),
    ]
