# Generated by Django 5.2.9 on 2026-01-05 22:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Negotiation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='active', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('accepted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='negotiations', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'negotiation',
                'verbose_name_plural': 'negotiations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('offered_by', models.CharField(choices=[('buyer', 'Buyer'), ('dealer', 'Dealer')], max_length=10)),
                ('message', models.TextField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('countered', 'Countered'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('negotiation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='negotiations.negotiation')),
            ],
            options={
                'verbose_name': 'offer',
                'verbose_name_plural': 'offers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='negotiation',
            index=models.Index(fields=['status', 'buyer'], name='negotiation_status_8cdde8_idx'),
        ),
        migrations.AddIndex(
            model_name='negotiation',
            index=models.Index(fields=['vehicle', 'status'], name='negotiation_vehicle_91832d_idx'),
        ),
        migrations.AddIndex(
            model_name='negotiation',
            index=models.Index(fields=['expires_at'], name='negotiation_expires_9362c8_idx'),
        ),
        migrations.AddConstraint(
            model_name='negotiation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('vehicle', 'buyer'), name='one_active_negotiation_per_buyer_vehicle'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['negotiation', '-created_at'], name='negotiation_negotia_3a6a1d_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['status'], name='negotiation_status_a055fc_idx'),
        ),
    ]
