# Generated by Django 5.2.9 on 2026-01-05 22:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vin', models.CharField(db_index=True, max_length=17, unique=True)),
                ('stock_number', models.CharField(max_length=50)),
                ('make', models.CharField(db_index=True, max_length=50)),
                ('model', models.CharField(db_index=True, max_length=100)),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('trim', models.CharField(blank=True, max_length=100)),
                ('body_type', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('truck', 'Truck'), ('coupe', 'Coupe'), ('hatchback', 'Hatchback'), ('convertible', 'Convertible'), ('van', 'Van'), ('wagon', 'Wagon')], max_length=20)),
                ('exterior_color', models.CharField(max_length=50)),
                ('interior_color', models.CharField(max_length=50)),
                ('msrp', models.DecimalField(decimal_places=2, max_digits=12)),
                ('floor_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('asking_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('features', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('pending_sale', 'Pending Sale'), ('sold', 'Sold'), ('inactive', 'Inactive')], default='draft', max_length=20)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='dealers.dealer')),
            ],
            options={
                'verbose_name': 'vehicle',
                'verbose_name_plural': 'vehicles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='vehicles/')),
                ('thumbnail_url', models.URLField(blank=True)),
                ('medium_url', models.URLField(blank=True)),
                ('large_url', models.URLField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'vehicle image',
                'verbose_name_plural': 'vehicle images',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['status', 'dealer'], name='vehicles_ve_status_a5e744_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['make', 'model', 'year'], name='vehicles_ve_make_2e7e5d_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['asking_price'], name='vehicles_ve_asking__f959be_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['body_type'], name='vehicles_ve_body_ty_fe2974_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['-created_at'], name='vehicles_ve_created_bb2812_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(condition=models.Q(('floor_price__lte', models.F('msrp'))), name='floor_price_lte_msrp'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(condition=models.Q(('asking_price__gte', models.F('floor_price'))), name='asking_price_gte_floor'),
        ),
    ]
