# Generated by Django 5.2.9 on 2026-01-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_savedvehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleimage',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='large',
            field=models.ImageField(blank=True, upload_to='vehicles/large/'),
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='medium',
            field=models.ImageField(blank=True, upload_to='vehicles/medium/'),
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='vehicles/thumbs/'),
        ),
    ]
